from libs.ui.Constants import Constants


class TIMEOUT(Constants):
    SECONDS_EXTRA_SHORT = 1
    SECONDS_SHORT = 5
    SECONDS_MEDIUM = 10
    SECONDS_LARGE = 30
    SECONDS_EXTRA_LARGE = 60
    MINUTES_EXTRA_SHORT = 1
    MINUTES_SHORT = 5
    MINUTES_MEDIUM = 10
    MINUTES_LARGE = 30
    MINUTES_EXTRA_LARGE = 60
